"""added multitenancy columns and keyword search columns

Revision ID: b0ff4ee492b5
Revises: 22821225bcad
Create Date: 2024-08-15 16:16:27.493330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import TSVECTOR

# revision identifiers, used by Alembic.
revision: str = 'b0ff4ee492b5'
down_revision: Union[str, None] = '22821225bcad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('alembic_version')
    op.add_column('langchain_pg_collection', sa.Column('tenant_id', sa.Integer(), nullable=False, server_default=str(2)))
    op.add_column('langchain_pg_collection', sa.Column('application_id', sa.Integer(), nullable=False, server_default=str(3)))
    op.add_column('langchain_pg_embedding', sa.Column('keywords_ts_vector', TSVECTOR(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('langchain_pg_embedding', 'keywords_ts_vector')
    op.drop_column('langchain_pg_collection', 'application_id')
    op.drop_column('langchain_pg_collection', 'tenant_id')
    # op.create_table('alembic_version',
    # sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    # )
    # ### end Alembic commands ###
