"""release 2.8 seq 1 change time to date in web table

Revision ID: cbf7b386206b
Revises: de28249e3550
Create Date: 2024-09-03 11:33:16.954748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import date


# revision identifiers, used by Alembic.
revision: str = 'cbf7b386206b'
down_revision: Union[str, None] = 'de28249e3550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('langchain_pg_web', sa.Column('date', sa.DATE(), server_default=sa.func.current_date(), nullable=False))
    op.drop_column('langchain_pg_web', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('langchain_pg_web', sa.Column('timestamp', sa.VARCHAR(), server_default=sa.func.current_timestamp(), nullable=False))
    op.drop_column('langchain_pg_web', 'date')
    
    # ### end Alembic commands ###
