"""release 2.9 seq 2 revert optional columns to mandatory columns in langchain collections table

Revision ID: e75cdf34bdf7
Revises: b0ff4ee492b5
Create Date: 2024-09-20 18:35:15.829763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e75cdf34bdf7'
down_revision: Union[str, None] = 'b0ff4ee492b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('langchain_pg_collection', 'tenant_id',
               existing_type=sa.Integer(),
               nullable=False,
               server_default=None)
    op.alter_column('langchain_pg_collection', 'application_id',
               existing_type=sa.Integer(),
               nullable=False,
               server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('langchain_pg_collection', 'application_id',
               existing_type=sa.Integer(),
               nullable=False,
               server_default=str(3))
    op.alter_column('langchain_pg_collection', 'tenant_id',
               existing_type=sa.Integer(),
               nullable=False,
               server_default=str(2))
    # ### end Alembic commands ###
