"""release 2.9 seq 5 add column embedding table for search

Revision ID: fecf2e29f617
Revises: 5ef1ad5f32fd
Create Date: 2024-11-28 17:24:12.513953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fecf2e29f617'
down_revision: Union[str, None] = '5ef1ad5f32fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('langchain_pg_embedding', sa.Column('adv_search_ts_vector', postgresql.TSVECTOR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('langchain_pg_embedding', 'adv_search_ts_vector')
    # ### end Alembic commands ###
